"""Metric-affine geometry (PDF item 11): ``∇``, torsion ``T``,
curvature ``R``, non-metricity ``Q``, connection/torsion/curvature
forms, Ricci, Ricci scalar, Einstein, Bianchi, Cartan structure
equations, Koszul, Schouten decomposition.

Phase 4.A ships the connection structure layer (direction-slot
``C^∞``-linearity + the engine); T/R/Q and the identities follow in
4.B-4.E.
"""

from jacopy.packages.metric_affine.bianchi import (
    covariant_curvature_derivative,
    covariant_jacobi_theorems,
    covariant_torsion_derivative,
    prove_bianchi_first,
    prove_bianchi_second,
    prove_ricci_identity_on_functions,
)
from jacopy.packages.metric_affine.e_connection import (
    ECurvatureExpansionDefinition,
    EConnectionScalarActionDefinition,
    ETorsionExpansionDefinition,
    e_connection,
    e_connection_engine,
    prove_e_connection_anchored_leibniz,
    prove_e_curvature_last_slot_conditional,
    prove_e_torsion_second_slot_tensorial,
    prove_pseudo_torsion_first_slot_defect,
)
from jacopy.packages.metric_affine.component_workflow import (
    ComponentInput,
)
from jacopy.packages.metric_affine.engine import metric_affine_engine
from jacopy.packages.metric_affine.modified import (
    CoframeRecombinationDefinition,
    modified_torsion,
    projected_curvature,
    prove_modified_torsion_tensorial,
    prove_projected_curvature_first_slot,
    prove_projected_curvature_last_slot,
)
from jacopy.packages.metric_affine.frame_components import (
    ConnectionCoefficient,
    ConnectionForm,
    ConnectionFormEvaluationDefinition,
    FrameConnectionCoefficientDefinition,
    FramePairingSplitDefinition,
    connection_coefficient,
    connection_form,
    curvature_component_formula,
    einstein_component,
    prove_cartan_first_evaluated,
    prove_cartan_first_structure,
    prove_cartan_second_structure,
    prove_curvature_components,
    prove_ricci_components,
    prove_ricci_scalar_components,
    ricci_component,
    ricci_scalar,
    prove_connection_form_on_frame,
    prove_torsion_components,
)
from jacopy.packages.metric_affine.koszul import (
    prove_generalized_koszul,
    prove_koszul_formula,
    prove_levi_civita_unique,
)
from jacopy.packages.metric_affine.metric import (
    as_metric_context,
    InverseMetricComponent,
    Metric,
    MetricCompatibilityDefinition,
    MetricInverseContractionDefinition,
    inverse_metric_component,
    MetricValue,
    MetricValueBilinearityDefinition,
    MetricValueSymmetryDefinition,
    NonMetricity,
    NonMetricityExpansionDefinition,
    TorsionFreeDefinition,
    metric,
    nonmetricity,
)
from jacopy.packages.metric_affine.rules import (
    ConnectionDirectionLinearityDefinition,
)
from jacopy.packages.metric_affine.torsion_curvature import (
    Curvature,
    CurvatureExpansionDefinition,
    Torsion,
    TorsionExpansionDefinition,
    curvature,
    prove_connection_difference_tensorial,
    prove_curvature_antisymmetry,
    prove_curvature_tensorial,
    prove_torsion_antisymmetry,
    prove_torsion_tensorial,
    torsion,
)

__all__ = [
    "ConnectionDirectionLinearityDefinition",
    "metric_affine_engine",
    "Curvature",
    "CurvatureExpansionDefinition",
    "Torsion",
    "TorsionExpansionDefinition",
    "curvature",
    "torsion",
    "prove_connection_difference_tensorial",
    "prove_curvature_antisymmetry",
    "prove_curvature_tensorial",
    "prove_torsion_antisymmetry",
    "prove_torsion_tensorial",
    "Metric",
    "MetricCompatibilityDefinition",
    "MetricValue",
    "MetricValueBilinearityDefinition",
    "MetricValueSymmetryDefinition",
    "NonMetricity",
    "NonMetricityExpansionDefinition",
    "TorsionFreeDefinition",
    "ComponentInput",
    "as_metric_context",
    "metric",
    "nonmetricity",
    "prove_generalized_koszul",
    "prove_koszul_formula",
    "prove_levi_civita_unique",
    "covariant_curvature_derivative",
    "covariant_jacobi_theorems",
    "covariant_torsion_derivative",
    "prove_bianchi_first",
    "prove_bianchi_second",
    "prove_ricci_identity_on_functions",
    "ConnectionCoefficient",
    "ConnectionForm",
    "ConnectionFormEvaluationDefinition",
    "FrameConnectionCoefficientDefinition",
    "FramePairingSplitDefinition",
    "connection_coefficient",
    "connection_form",
    "prove_cartan_first_evaluated",
    "prove_cartan_first_structure",
    "prove_cartan_second_structure",
    "prove_curvature_components",
    "prove_ricci_components",
    "curvature_component_formula",
    "ricci_component",
    "ricci_scalar",
    "einstein_component",
    "prove_ricci_scalar_components",
    "InverseMetricComponent",
    "MetricInverseContractionDefinition",
    "inverse_metric_component",
    "ECurvatureExpansionDefinition",
    "EConnectionScalarActionDefinition",
    "ETorsionExpansionDefinition",
    "e_connection",
    "e_connection_engine",
    "prove_e_connection_anchored_leibniz",
    "prove_e_curvature_last_slot_conditional",
    "prove_e_torsion_second_slot_tensorial",
    "prove_pseudo_torsion_first_slot_defect",
    "CoframeRecombinationDefinition",
    "modified_torsion",
    "projected_curvature",
    "prove_modified_torsion_tensorial",
    "prove_projected_curvature_first_slot",
    "prove_projected_curvature_last_slot",
    "prove_connection_form_on_frame",
    "prove_torsion_components",
]
