"""
Admissible E-connections (Phase 4.F.1) — the admissible-connections
paper (Dereli-Doğan, J. Geom. Phys. 186 (2023); "ADM" below).

On a local almost-Leibniz algebroid ``(E, ρ, [·,·]_E, L)`` a linear
E-connection ``∇`` is **admissible** [ADM Def 3.4] iff

    [u,v]_E + [v,u]_E = Σ_s L(e^s, ∇_{e_s}u, v)
                       + Σ_s L(e^s, ∇_{e_s}v, u),

i.e. the bracket's symmetric part is generated by ``L`` through
``∇``. An algebroid admitting such a connection is *anti-commutable*
[ADM Def 3.3]. Admissibility is a STRUCTURE-PAIR property (bracket +
connection), so it enters proofs only through the opt-in
:class:`AdmissibilityDeclaration` — the exact analogue of the C2
symmetric-part declaration, in the same collection direction (a
single-bracket swap orientation would re-create the Phase 3.E.2
rewrite cycle).

Mechanical theorems of this pass:

* **[ADM Prop 3.3]** modified-torsion-freeness forces admissibility:
  under the ``ᴸT = 0`` declaration (:class:`
  ModifiedTorsionFreeDeclaration`, which solves ``ᴸT = 0`` for the
  bracket in the expansion direction) the admissibility equation is
  a theorem.
* **[ADM Cor 3.2]** the modified torsion of an admissible connection
  is antisymmetric — proved in symmetric-part form
  ``ᴸT(u,v) + ᴸT(v,u) = 0`` (the difference shape lets the
  collection declaration fire; the two sides separately have no
  common normal form, by design of the collection-only direction).
* **[ADM Prop 3.2, dull part]** the modified bracket
  ``[u,v]^∇ := [u,v]_E − Σ_s L(e^s, ∇_{e_s}u, v)`` satisfies the
  EXACT left-Leibniz rule ``[fu,v]^∇ = f[u,v]^∇ − ρ(v)(f)u`` for ANY
  connection (no declaration): the coframe recombination cancels the
  locality defect. The modified pair ``(E, ρ, [·,·]^∇, L=0)`` is an
  almost-dull algebroid.
"""

from __future__ import annotations

from typing import Optional

from jacopy.algebra.derivation import Act
from jacopy.core.expr import Expr, Neg, Product, Rational, Sum
from jacopy.core.indexed_sum import IndexedSum
from jacopy.core.registry import PropertyRegistry
from jacopy.proof.chain import ProofChain
from jacopy.proof.expansion import Definition
from jacopy.proof.step import ProofStep
from jacopy.proof.strategies import ExpandAndSimplify
from jacopy.central.objects.connection import Connection
from jacopy.central.objects.frame import Frame, FrameIndex
from jacopy.central.algebroid.context import (
    Algebroid,
    AlgebroidBracket,
    LocalityOperator,
)
from jacopy.central.algebroid.declarations import (
    SymmetricPartDeclaration,
)
from jacopy.packages.metric_affine.modified import (
    _engine,
    modified_torsion,
)


def _locality_sum(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    bound: str,
) -> Expr:
    """``Σ_s L(e^s, ∇_{e_s}u, v)`` — the admissibility generator."""
    return IndexedSum(
        FrameIndex(bound),
        fr,
        LocalityOperator(
            alg.name,
            fr.dual().field(bound),
            conn(fr.field(bound), u),
            v,
        ),
    )


def modified_bracket(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    *,
    bound: str = "s",
) -> Expr:
    """``[u,v]^∇ := [u,v]_E − Σ_s L(e^s, ∇_{e_s}u, v)``
    [ADM eq (3.12) with the canonical representative]."""
    if fr.bundle != alg.bundle:
        raise ValueError(
            "the frame must live on the algebroid's bundle"
        )
    return Sum(
        alg.bracket(u, v),
        Neg(_locality_sum(alg, conn, fr, u, v, bound)),
    )


class AdmissibilityDeclaration(SymmetricPartDeclaration):
    """The admissibility axiom [ADM Def 3.4], applied in the
    COLLECTION direction: a same-signed transposed bracket pair
    ``±(c·[a,b] … c·[b,a])`` inside a sum is replaced by
    ``±c·(Σ_s L(e^s,∇_{e_s}a,b) + Σ_s L(e^s,∇_{e_s}b,a))``, and the
    equal-slot summand ``c·[u,u]`` by half of it. Collection shapes
    and cycle-avoidance rationale inherited from the C2
    :class:`SymmetricPartDeclaration`."""

    def __init__(
        self,
        alg: Algebroid,
        conn: Connection,
        fr: Frame,
        *,
        bound: str = "s",
    ) -> None:
        super().__init__(alg)
        if fr.bundle != alg.bundle:
            raise ValueError(
                "the frame must live on the algebroid's bundle"
            )
        self._conn = conn
        self._fr = fr
        self._bound = bound
        self.name = (
            f"admissible connection ({alg.name}, {conn.name}): "
            "[u,v] + [v,u] = ΣL(e^s,∇u,v) + ΣL(e^s,∇v,u)"
        )

    def rewrite(self, expr: Expr) -> Expr:
        indices, sign, cofactors, br, half = self._find_collection(
            expr
        )
        a, b = br.u, br.v
        if a._repr_inner() > b._repr_inner():
            a, b = b, a
        correction: Expr = Sum(
            _locality_sum(
                self._alg, self._conn, self._fr, a, b, self._bound
            ),
            _locality_sum(
                self._alg, self._conn, self._fr, b, a, self._bound
            ),
        )
        factors = ((Rational(1, 2),) if half else ()) + tuple(
            cofactors
        )
        if factors:
            correction = Product(*factors, correction)
        if sign < 0:
            correction = Neg(correction)
        rest = [
            t
            for k, t in enumerate(expr.children)
            if k not in indices
        ]
        if not rest:
            return correction
        return Sum(*rest, correction)


class ModifiedTorsionFreeDeclaration(Definition):
    """``ᴸT(∇) = 0`` declared, solved for the bracket in the
    expansion direction:

        [u,v]_E → ∇_u v − ∇_v u + Σ_s L(e^s, ∇_{e_s}u, v).

    The right-hand side contains no bracket, so the rewrite
    terminates; the recombination rule collects a different shape,
    so no ping-pong."""

    anchor = AlgebroidBracket

    def __init__(
        self,
        alg: Algebroid,
        conn: Connection,
        fr: Frame,
        *,
        bound: str = "s",
    ) -> None:
        self._alg = alg
        self._conn = conn
        self._fr = fr
        self._bound = bound
        self.name = (
            f"declared ᴸT-free ({alg.name}, {conn.name}): "
            "[u,v] = ∇_u v − ∇_v u + ΣL(e^s,∇u,v)"
        )

    def matches(self, expr: Expr) -> bool:
        return (
            isinstance(expr, AlgebroidBracket)
            and expr.algebroid_name == self._alg.name
        )

    def rewrite(self, expr: Expr) -> Expr:
        u, v = expr.u, expr.v
        return Sum(
            self._conn(u, v),
            Neg(self._conn(v, u)),
            _locality_sum(
                self._alg, self._conn, self._fr, u, v, self._bound
            ),
        )


# --------------------------------------------------------------------- #
# The Courant link (Phase 4.F.2) [MC Prop 4.1, ADM Prop 3.5]            #
# --------------------------------------------------------------------- #


class CourantLocalityDefinition(Definition):
    """``ᵍL(Ω, u, v) → g(u,v)·g⁻¹(Ω)`` [MC Prop 4.1]: on an
    almost-Courant algebroid the locality operator is generated by
    the E-metric. Expansion direction (metric/sharp outputs never
    re-create an ``L`` node)."""

    anchor = LocalityOperator

    def __init__(self, alg: Algebroid) -> None:
        if alg.is_tangent:
            raise ValueError(
                "the tangent algebroid carries no E-metric/locality "
                "layer"
            )
        self._alg = alg
        self.name = (
            f"Courant locality ({alg.name}): "
            "L(Ω,u,v) = g(u,v)·g⁻¹(Ω)"
        )

    def matches(self, expr: Expr) -> bool:
        return (
            isinstance(expr, LocalityOperator)
            and expr.algebroid_name == self._alg.name
        )

    def rewrite(self, expr: Expr) -> Expr:
        form, u, v = expr.rewritable_slots
        return Product(
            self._alg.metric(u, v), self._alg.sharp(form)
        )


class MetricCompatibilityCollection(Definition):
    """Declared metric compatibility ``Q(∇, g) = 0`` in the
    COLLECTION direction, across a framed pair of indexed sums:

        Σ_s c(s)·g(∇_{e_s}a, b) + Σ_s c(s)·g(∇_{e_s}b, a)
            → Σ_s c(s)·ρ(e_s)(g(a,b))

    (with a common body cofactor tuple ``c(s)``, e.g. ``g⁻¹(e^s)``).
    A swap orientation would cycle against the coboundary pairing —
    same design decision as the C2/admissibility collections. The
    output body is a Product of bound factors, so the indexed-sum
    linearity split cannot undo it (no ping-pong)."""

    anchor = Sum

    def __init__(self, alg: Algebroid, conn: Connection) -> None:
        self._alg = alg
        self._conn = conn
        self.name = (
            f"declared metric compatibility ({alg.name}, "
            f"{conn.name}): g(∇_x a, b) + g(a, ∇_x b) = ρ(x)(g(a,b))"
        )

    def _metric_body(self, term: Expr):
        """``(sign, dummy, range, cofactors, x, cov_arg, plain)`` for
        a term carrying exactly one E-metric factor with one
        ``∇_x``-applied slot — either inside an IndexedSum over a
        frame direction (``dummy`` = the bound name) or as a PLAIN
        summand with an arbitrary direction (``dummy = range =
        None``)."""
        from jacopy.central.algebroid.context import EMetric
        from jacopy.central.objects.connection import CovariantOp
        from jacopy.central.objects.frame import FrameField

        sign = 1
        core = term
        if isinstance(core, Neg):
            sign = -1
            core = core.arg
        if isinstance(core, IndexedSum):
            dummy = core.dummy._repr_inner()
            range_ = core.range_
            body = core.body
        else:
            dummy = None
            range_ = None
            body = core
        factors = (
            list(body.children)
            if isinstance(body, Product)
            else [body]
        )
        metrics = [
            (k, c)
            for k, c in enumerate(factors)
            if isinstance(c, EMetric)
            and c.algebroid_name == self._alg.name
        ]
        if len(metrics) != 1:
            return None
        k, m = metrics[0]
        cofactors = tuple(
            c for j, c in enumerate(factors) if j != k
        )

        def _cov_split(slot_a: Expr, slot_b: Expr):
            if not (
                isinstance(slot_a, Act)
                and isinstance(slot_a.op, CovariantOp)
                and slot_a.op.connection_name == self._conn.name
            ):
                return None
            direction = slot_a.op.vector
            if dummy is not None and not (
                isinstance(direction, FrameField)
                and direction.index == dummy
            ):
                return None
            return direction, slot_a.arg, slot_b

        split = _cov_split(m.u, m.v) or _cov_split(m.v, m.u)
        if split is None:
            return None
        x, cov_arg, plain = split
        return sign, dummy, range_, cofactors, x, cov_arg, plain

    @staticmethod
    def _cofactor_key(cofactors):
        return tuple(sorted(c._repr_inner() for c in cofactors))

    def _find_pair(self, expr: Sum):
        terms = expr.children
        for i, ti in enumerate(terms):
            si = self._metric_body(ti)
            if si is None:
                continue
            for j in range(i + 1, len(terms)):
                sj = self._metric_body(terms[j])
                if sj is None:
                    continue
                if (
                    si[0] == sj[0]
                    and si[1] == sj[1]
                    and si[2] == sj[2]
                    and si[4] == sj[4]
                    and self._cofactor_key(si[3])
                    == self._cofactor_key(sj[3])
                    and si[5] == sj[6]
                    and si[6] == sj[5]
                ):
                    return (i, j), si
        return None

    def matches(self, expr: Expr) -> bool:
        return isinstance(expr, Sum) and self._find_pair(expr) is not None

    def rewrite(self, expr: Expr) -> Expr:
        (i, j), (sign, dummy, fr, cofactors, x, a, b) = (
            self._find_pair(expr)
        )
        from jacopy.central.objects.frame import FrameIndex

        if a._repr_inner() > b._repr_inner():
            a, b = b, a
        body: Expr = Act(
            self._alg.anchor(x), self._alg.metric(a, b)
        )
        if cofactors:
            body = Product(body, *cofactors)
        collected: Expr = (
            body
            if dummy is None
            else IndexedSum(FrameIndex(dummy), fr, body)
        )
        if sign < 0:
            collected = Neg(collected)
        rest = [
            t for k, t in enumerate(expr.children) if k not in (i, j)
        ]
        if not rest:
            return collected
        return Sum(*rest, collected)


# --------------------------------------------------------------------- #
# Theorems                                                               #
# --------------------------------------------------------------------- #


def prove_torsion_free_implies_admissible(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    *,
    registry: Optional[PropertyRegistry] = None,
) -> ProofChain:
    """[ADM Prop 3.3]: under the declared ``ᴸT(∇) = 0`` the
    admissibility equation
    ``[u,v] + [v,u] = ΣL(e^s,∇u,v) + ΣL(e^s,∇v,u)`` closes
    mechanically (the ``∇`` terms cancel pairwise)."""
    engine = _engine(alg, fr, registry)
    engine.register(
        ModifiedTorsionFreeDeclaration(alg, conn, fr)
    )
    lhs = Sum(alg.bracket(u, v), alg.bracket(v, u))
    rhs = Sum(
        _locality_sum(alg, conn, fr, u, v, "s"),
        _locality_sum(alg, conn, fr, v, u, "s"),
    )
    return ExpandAndSimplify().prove(
        lhs, rhs, registry=registry, engine=engine
    )


def prove_modified_torsion_symmetric_part_vanishes(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    *,
    registry: Optional[PropertyRegistry] = None,
) -> ProofChain:
    """[ADM Cor 3.2] in symmetric-part form:
    ``ᴸT(u,v) + ᴸT(v,u) = 0`` for an ADMISSIBLE connection (the
    declaration collects the transposed bracket pair). Honest fail
    without the declaration (tested)."""
    engine = _engine(alg, fr, registry)
    engine.register(AdmissibilityDeclaration(alg, conn, fr))
    lhs = Sum(
        modified_torsion(alg, conn, fr, u, v),
        modified_torsion(alg, conn, fr, v, u),
    )
    from jacopy.core.expr import Integer

    return ExpandAndSimplify().prove(
        lhs, Integer(0), registry=registry, engine=engine
    )


def prove_courant_locality_generator(
    alg: Algebroid,
    fr: Frame,
    u: Expr,
    v: Expr,
    f: Expr,
    *,
    registry: Optional[PropertyRegistry] = None,
) -> ProofChain:
    """[MC Prop 4.1 / Bourbaki eq (4.8)]: the almost-Courant
    symmetric part ``S(u,v) := g⁻¹(D g(u,v))`` satisfies the local
    consistency condition with the metric-generated locality
    operator:

        S(f·u, v) = f·S(u, v) + ᵍL(Df, u, v).

    Mechanism: metric bilinearity + coboundary Leibniz + sharp
    linearity + the ᵍL rule."""
    from jacopy.central.algebroid.rules import (
        CoboundaryLinearityDefinition,
    )

    engine = _engine(alg, fr, registry)
    engine.register(CourantLocalityDefinition(alg))
    engine.register(CoboundaryLinearityDefinition(alg, registry))
    lhs = alg.sharp(alg.D(alg.metric(Product(f, u), v)))
    rhs = Sum(
        Product(f, alg.sharp(alg.D(alg.metric(u, v)))),
        LocalityOperator(alg.name, alg.D(f), u, v),
    )
    return ExpandAndSimplify().prove(
        lhs, rhs, registry=registry, engine=engine
    )


def prove_metric_compatible_implies_admissible(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    *,
    registry: Optional[PropertyRegistry] = None,
) -> ProofChain:
    """[ADM Prop 3.5, ⟸ direction]: on an almost-Courant algebroid
    (locality = ᵍL), a METRIC-COMPATIBLE connection satisfies the
    admissibility equation:

        Σ_s ᵍL(e^s, ∇_{e_s}u, v) + Σ_s ᵍL(e^s, ∇_{e_s}v, u)
            = g⁻¹(D g(u,v))   (the C2 symmetric part).

    Mechanism: ᵍL rule → framed compatibility collection → coframe
    recombination (with ``E = g⁻¹``). The ⟹ direction needs the
    non-degeneracy stripping tactic — 4.F.2b. Honest fail without
    the compatibility declaration (tested)."""
    engine = _engine(alg, fr, registry)
    engine.register(CourantLocalityDefinition(alg))
    engine.register(MetricCompatibilityCollection(alg, conn))
    lhs = Sum(
        _locality_sum(alg, conn, fr, u, v, "s"),
        _locality_sum(alg, conn, fr, v, u, "s"),
    )
    rhs = alg.sharp(alg.D(alg.metric(u, v)))
    return ExpandAndSimplify().prove(
        lhs, rhs, registry=registry, engine=engine
    )


def prove_admissible_implies_metric_compatible(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    *,
    direction: str = "a",
    registry: Optional[PropertyRegistry] = None,
) -> ProofChain:
    """[ADM Prop 3.5, ⟹ direction — completes the equivalence]: on
    an almost-Courant algebroid, an ADMISSIBLE connection is
    metric-compatible on the frame directions:

        ρ(e_a)(g(u,v)) = g(∇_{e_a}u, v) + g(u, ∇_{e_a}v).

    Two-leg tactic (the 3.D pattern): the bracket's symmetric part
    ``S = [u,v] + [v,u]`` is expanded once through the C2
    symmetric-part axiom (→ ``g⁻¹Dg``) and once through the
    admissibility declaration (→ ``ΣᵍL``); the two results are
    combined and paired with the frame direction ``e_a`` — both
    pairings evaluate mechanically (sharp evaluation + coboundary
    pairing on the left; ᵍL + frame duality + Kronecker contraction
    on the right). The combine and congruence steps are explicitly
    labeled synthetic inferences."""
    from jacopy.central.tangent.definitions import (
        FrameDualityDefinition,
    )

    e_dir = fr.field(direction)
    S = Sum(alg.bracket(u, v), alg.bracket(v, u))
    c2_form = alg.sharp(alg.D(alg.metric(u, v)))
    adm_form = Sum(
        _locality_sum(alg, conn, fr, u, v, "s"),
        _locality_sum(alg, conn, fr, v, u, "s"),
    )

    eng1 = _engine(alg, fr, registry)
    eng1.register(SymmetricPartDeclaration(alg))
    leg1 = ExpandAndSimplify().prove(
        S, c2_form, registry=registry, engine=eng1
    )
    step1 = ProofStep(
        S,
        c2_form,
        rule="symmetric part (C2, almost-Courant axiom)",
        justification="[u,v] + [v,u] = g⁻¹(D g(u,v))",
    )
    for s in leg1:
        step1.add_child(s)

    eng2 = _engine(alg, fr, registry)
    eng2.register(AdmissibilityDeclaration(alg, conn, fr))
    leg2 = ExpandAndSimplify().prove(
        S, adm_form, registry=registry, engine=eng2
    )
    step2 = ProofStep(
        S,
        adm_form,
        rule="declared admissibility",
        justification="[u,v] + [v,u] = ΣᵍL(e^s,∇u,v) + ΣᵍL(e^s,∇v,u)",
    )
    for s in leg2:
        step2.add_child(s)

    step3 = ProofStep(
        c2_form,
        adm_form,
        rule="combine the two legs",
        justification=(
            "both equal the symmetric part [u,v] + [v,u]"
        ),
    )
    lhs_paired = alg.metric(c2_form, e_dir)
    rhs_paired = alg.metric(adm_form, e_dir)
    step4 = ProofStep(
        lhs_paired,
        rhs_paired,
        rule="congruence: apply g(·, e_a) to both sides",
        justification="g is a well-defined map on sections",
    )

    eng3 = _engine(alg, fr, registry)
    target_lhs = Act(alg.anchor(e_dir), alg.metric(u, v))
    leg3 = ExpandAndSimplify().prove(
        lhs_paired, target_lhs, registry=registry, engine=eng3
    )
    step5 = ProofStep(
        lhs_paired,
        target_lhs,
        rule="evaluate the C2 side",
        justification="sharp evaluation + coboundary pairing",
    )
    for s in leg3:
        step5.add_child(s)

    eng4 = _engine(alg, fr, registry)
    eng4.register(CourantLocalityDefinition(alg))
    eng4.register(FrameDualityDefinition())
    target_rhs = Sum(
        alg.metric(conn(e_dir, u), v),
        alg.metric(conn(e_dir, v), u),
    )
    leg4 = ExpandAndSimplify().prove(
        rhs_paired, target_rhs, registry=registry, engine=eng4
    )
    step6 = ProofStep(
        rhs_paired,
        target_rhs,
        rule="evaluate the admissibility side",
        justification=(
            "ᵍL + frame duality + Kronecker contraction"
        ),
    )
    for s in leg4:
        step6.add_child(s)

    step7 = ProofStep(
        target_lhs,
        target_rhs,
        rule="metric compatibility on the frame direction",
        justification=(
            "chain the evaluated sides: ρ(e_a)(g(u,v)) = "
            "g(∇_{e_a}u,v) + g(u,∇_{e_a}v)"
        ),
    )
    return ProofChain(
        [step1, step2, step3, step4, step5, step6, step7]
    )


def prove_modified_bracket_left_leibniz(
    alg: Algebroid,
    conn: Connection,
    fr: Frame,
    u: Expr,
    v: Expr,
    f: Expr,
    *,
    registry: Optional[PropertyRegistry] = None,
) -> ProofChain:
    """[ADM Prop 3.2, dull part]: for ANY linear E-connection,

        [f·u, v]^∇ = f·[u,v]^∇ − ρ(v)(f)·u

    — the locality defect of the left-Leibniz rule is cancelled by
    the recombined correction, so the modified pair
    ``(E, ρ, [·,·]^∇, L=0)`` is almost-dull. No declaration."""
    lhs = modified_bracket(alg, conn, fr, Product(f, u), v)
    rhs = Sum(
        Product(f, modified_bracket(alg, conn, fr, u, v)),
        Neg(Product(Act(alg.anchor(v), f), u)),
    )
    return ExpandAndSimplify().prove(
        lhs,
        rhs,
        registry=registry,
        engine=_engine(alg, fr, registry),
    )
