"""Central code — the algebroid case (PDF item 10; Phase 3).

Anchored vector bundles, the opaque algebroid bracket and coboundary
(3.A); the declared property hierarchy, Jacobiator/Derivator/Predator,
locality and the algebroid calculus arrive with 3.B-3.F. Sources:
in-repo ``pre-metric-bourbaki.pdf`` and ``metric-connection.pdf``.
"""

from jacopy.central.algebroid.context import (
    DECLARATIONS,
    LEVELS,
    Algebroid,
    AlgebroidBracket,
    AnchoredVF,
    CoboundaryForm,
    EMetric,
    LocalityOperator,
    MetricSharp,
    algebroid,
    locality_term,
    tangent_algebroid,
)
from jacopy.central.algebroid.declarations import (
    AnchorMorphismDeclaration,
    JacobiDeclaration,
    LeftLeibnizDeclaration,
    MetricInvarianceDeclaration,
    RightLeibnizDeclaration,
    SymmetricPartDeclaration,
    declaration_rules,
)
from jacopy.central.algebroid.operators import (
    Derivator,
    DerivatorExpansionDefinition,
    Jacobiator,
    JacobiatorExpansionDefinition,
    MappedSection,
    MappedSectionLinearityDefinition,
    Predator,
    PredatorExpansionDefinition,
    SectionMap,
    anchor_predator,
    derivator,
    jacobiator,
    predator,
    section_map,
)
from jacopy.central.algebroid.rules import (
    AnchorLinearityDefinition,
    BracketBilinearityDefinition,
    CoboundaryLinearityDefinition,
    CoboundaryPairingDefinition,
    LocalityMultilinearityDefinition,
    MetricBilinearityDefinition,
    MetricSharpEvaluationDefinition,
    MetricSharpLinearityDefinition,
    MetricSymmetryDefinition,
)
from jacopy.central.algebroid.calculus import (
    algebroid_calculus,
    d_E,
    jacobi_combination_theorem,
    lie_E,
    prove_cartan_magic_on_functions,
    prove_cartan_magic_on_one_forms,
    prove_d_coincides_with_coboundary,
    prove_d_on_functions,
    prove_d_squared_zero_on_functions,
    prove_d_squared_zero_on_one_forms,
    prove_lie_core_cases,
    prove_palais_on_one_forms,
)
from jacopy.central.algebroid.engine import algebroid_engine
from jacopy.central.algebroid.locality import (
    LocalityProjector,
    LocalityProjectorAbsorptionDefinition,
    LocalityProjectorKernelDefinition,
    locality_projector,
)
from jacopy.central.algebroid.theorems import (
    prove_anchor_morphism,
    prove_anchor_predator_vanishes,
    prove_left_leibniz_from_metric,
    prove_locality_anchor_annihilation,
    prove_right_leibniz_from_metric,
)

__all__ = [
    "DECLARATIONS",
    "LEVELS",
    "EMetric",
    "LocalityOperator",
    "MetricSharp",
    "locality_term",
    "MetricInvarianceDeclaration",
    "SymmetricPartDeclaration",
    "MetricBilinearityDefinition",
    "MetricSharpEvaluationDefinition",
    "MetricSharpLinearityDefinition",
    "MetricSymmetryDefinition",
    "AnchorMorphismDeclaration",
    "JacobiDeclaration",
    "LeftLeibnizDeclaration",
    "RightLeibnizDeclaration",
    "declaration_rules",
    "Jacobiator",
    "JacobiatorExpansionDefinition",
    "jacobiator",
    "Derivator",
    "DerivatorExpansionDefinition",
    "MappedSection",
    "MappedSectionLinearityDefinition",
    "Predator",
    "PredatorExpansionDefinition",
    "SectionMap",
    "anchor_predator",
    "derivator",
    "predator",
    "section_map",
    "Algebroid",
    "AlgebroidBracket",
    "AnchoredVF",
    "CoboundaryForm",
    "algebroid",
    "tangent_algebroid",
    "AnchorLinearityDefinition",
    "BracketBilinearityDefinition",
    "CoboundaryLinearityDefinition",
    "CoboundaryPairingDefinition",
    "LocalityMultilinearityDefinition",
    "algebroid_engine",
    "prove_anchor_morphism",
    "prove_anchor_predator_vanishes",
    "prove_left_leibniz_from_metric",
    "prove_locality_anchor_annihilation",
    "prove_right_leibniz_from_metric",
    "LocalityProjector",
    "LocalityProjectorAbsorptionDefinition",
    "LocalityProjectorKernelDefinition",
    "locality_projector",
    "algebroid_calculus",
    "d_E",
    "lie_E",
    "jacobi_combination_theorem",
    "prove_cartan_magic_on_functions",
    "prove_cartan_magic_on_one_forms",
    "prove_d_coincides_with_coboundary",
    "prove_d_on_functions",
    "prove_d_squared_zero_on_functions",
    "prove_d_squared_zero_on_one_forms",
    "prove_lie_core_cases",
    "prove_palais_on_one_forms",
]
