"""Generalized geometry (PDF item 14; Phase 7).

Courant algebroid axiomatics + the Uchino redundancy theorems
(uchino.pdf, math/0204010); Dorfman & Courant bracket property
suites, H-twists and the Roytenberg family arrive from the Phase 6
drinfeld package as this phase proceeds."""

from jacopy.packages.generalized.courant_axioms import (
    C3IdentityDeclaration,
    CourantD,
    CourantInvarianceDeclaration,
    DDZeroDefinition,
    DLeibnizDefinition,
    DNumericHomogeneityDeclaration,
    DPairingUnfoldDefinition,
    SkewSwapCompositeDefinition,
    courant_context,
    courant_engine,
    prove_anchor_annihilates_d,
    prove_bracket_with_d,
    prove_d_numeric_homogeneity,
    prove_d_pairing_formula,
    prove_left_leibniz_c3,
    prove_leibniz_from_c3,
)
from jacopy.packages.generalized.dorfman_axioms import (
    dorfman_axiom_context,
    prove_dorfman_c2_redundant,
    prove_dorfman_c3_redundant,
)
from jacopy.packages.generalized.twisted_courant import (
    courant_bracket_h,
    prove_severa_twist_is_courant,
    prove_twisted_anchor_morphism,
    prove_twisted_courant_dorfman_relation,
    prove_twisted_invariance,
    prove_twisted_jacobi_dh_defect,
    prove_twisted_right_leibniz,
    prove_twisted_symmetric_part,
)
from jacopy.packages.generalized.poisson_generalized import (
    d_operator_theta,
    poisson_base,
    prove_theta_anchor_morphism,
    prove_theta_courant_skew,
    prove_theta_d_pairing_value,
    prove_theta_invariance,
    theta_anchor,
    theta_courant,
    theta_dorfman,
)
from jacopy.packages.generalized.r_twisted import (
    prove_derived_r_vanishes_under_poisson,
    prove_r_anchor_defect,
    prove_r_twisted_courant_relation,
    prove_r_twisted_right_leibniz,
    prove_r_twisted_symmetric_part,
    r_term,
    r_twisted_theta_dorfman,
)
from jacopy.packages.generalized.roytenberg_courant import (
    prove_full_roytenberg_symmetric_part,
    prove_roytenberg_h_is_twisted_dorfman,
    prove_roytenberg_is_theta_double_under_poisson,
    prove_roytenberg_reduces_to_dorfman,
)
from jacopy.packages.generalized.frame_evaluation import (
    prove_anchor_components,
    prove_basis_pairing_components,
    prove_dorfman_form_components,
    prove_dorfman_vector_components,
    prove_theta_koszul_components,
)
from jacopy.packages.generalized.bourbaki_precalculus import (
    BourbakiPreCalculus,
    bourbaki_engine,
    prove_cartan_satisfies_914,
    prove_cartan_satisfies_915,
    prove_standard_metric_invariance,
    prove_standard_symmetric_part,
    standard_bracket,
    standard_metric,
)
from jacopy.packages.generalized.bourbaki_structure import (
    bourbaki_structure_context,
    bourbaki_structure_engine,
    prove_left_leibniz_bourbaki,
    prove_locality_is_symbol,
    prove_right_leibniz_from_r_invariance,
)
from jacopy.packages.generalized.bourbaki_exact import (
    exact_bourbaki_context,
    exact_bourbaki_engine,
    prove_911,
    prove_912,
    prove_lemma_91,
)
from jacopy.packages.generalized.bourbaki_severa import (
    prove_chi_chi_bracket_vanishes,
    prove_chi_phi_bracket,
    prove_delta_first_slot_anomaly,
    prove_delta_lands_in_chi,
    prove_delta_tensorial_second_slot,
    prove_h_antisymmetric_for_isotropic_phi,
)
from jacopy.packages.generalized.standard_courant import (
    courant_bracket_std,
    courant_jacobiator_std,
    courant_t_scalar_std,
    d_operator_std,
    prove_anchor_morphism_std,
    prove_courant_c3_lwx_std,
    prove_courant_dorfman_relation,
    prove_courant_jacobi_dt_std,
    prove_courant_skew_std,
    prove_dorfman_invariance_std,
)

__all__ = [
    "C3IdentityDeclaration",
    "CourantD",
    "CourantInvarianceDeclaration",
    "DDZeroDefinition",
    "DLeibnizDefinition",
    "DNumericHomogeneityDeclaration",
    "DPairingUnfoldDefinition",
    "SkewSwapCompositeDefinition",
    "BourbakiPreCalculus",
    "bourbaki_engine",
    "bourbaki_structure_context",
    "bourbaki_structure_engine",
    "courant_bracket_h",
    "courant_bracket_std",
    "courant_context",
    "courant_engine",
    "courant_jacobiator_std",
    "courant_t_scalar_std",
    "d_operator_std",
    "d_operator_theta",
    "dorfman_axiom_context",
    "exact_bourbaki_context",
    "exact_bourbaki_engine",
    "poisson_base",
    "prove_911",
    "prove_chi_chi_bracket_vanishes",
    "prove_chi_phi_bracket",
    "prove_delta_first_slot_anomaly",
    "prove_delta_lands_in_chi",
    "prove_delta_tensorial_second_slot",
    "prove_h_antisymmetric_for_isotropic_phi",
    "prove_912",
    "prove_anchor_components",
    "prove_anchor_morphism_std",
    "prove_basis_pairing_components",
    "prove_cartan_satisfies_914",
    "prove_cartan_satisfies_915",
    "prove_dorfman_form_components",
    "prove_dorfman_vector_components",
    "prove_theta_koszul_components",
    "prove_courant_c3_lwx_std",
    "prove_courant_dorfman_relation",
    "prove_courant_jacobi_dt_std",
    "prove_courant_skew_std",
    "prove_dorfman_invariance_std",
    "prove_anchor_annihilates_d",
    "prove_bracket_with_d",
    "prove_d_numeric_homogeneity",
    "prove_d_pairing_formula",
    "prove_derived_r_vanishes_under_poisson",
    "prove_dorfman_c2_redundant",
    "prove_dorfman_c3_redundant",
    "prove_full_roytenberg_symmetric_part",
    "prove_left_leibniz_bourbaki",
    "prove_lemma_91",
    "prove_left_leibniz_c3",
    "prove_locality_is_symbol",
    "prove_r_anchor_defect",
    "prove_right_leibniz_from_r_invariance",
    "prove_roytenberg_h_is_twisted_dorfman",
    "prove_roytenberg_is_theta_double_under_poisson",
    "prove_roytenberg_reduces_to_dorfman",
    "prove_r_twisted_courant_relation",
    "prove_r_twisted_right_leibniz",
    "prove_r_twisted_symmetric_part",
    "prove_severa_twist_is_courant",
    "prove_standard_metric_invariance",
    "prove_standard_symmetric_part",
    "standard_bracket",
    "standard_metric",
    "prove_twisted_anchor_morphism",
    "prove_twisted_courant_dorfman_relation",
    "prove_twisted_invariance",
    "prove_twisted_jacobi_dh_defect",
    "prove_twisted_right_leibniz",
    "prove_theta_anchor_morphism",
    "prove_theta_courant_skew",
    "prove_theta_d_pairing_value",
    "prove_theta_invariance",
    "prove_twisted_symmetric_part",
    "r_term",
    "r_twisted_theta_dorfman",
    "theta_anchor",
    "theta_courant",
    "theta_dorfman",
    "prove_leibniz_from_c3",
]
